name: "Windows: cl"

on:
  push:
    branches: [ "main" ]
    paths:
     - '**/*.cpp'
     - '**/*.h'
  pull_request:
    branches: [ "main" ]
    paths:
     - '**/*.cpp'
     - '**/*.h'

env:
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
