name: "Linux: GCC on ARM64"

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/CMakeLists.txt'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
    # clone --recursive
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          qemu-user-static \
          binfmt-support

    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../resources/toolchain-arm64.cmake ..

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests with QEMU
      run: |
        cd build
        qemu-aarch64 ./coltcpp_tests