name: "Linux: GCC on ARM64"

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '**/*.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '**/*.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
    # clone --recursive
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qemu-user-static \
          binfmt-support
        wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        tar xvf arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        echo "$HOME/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin" >> $GITHUB_PATH
        echo "CC=arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX=arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-g++" >> $GITHUB_ENV
        
    - name: ECHO
      run: |
        echo "$CXX"
        echo "$CC"
        cat "$GITHUB_PATH"

    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../resources/toolchain-arm64.cmake ..

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests with QEMU
      run: |
        cd build
        qemu-aarch64-static ./coltcpp_tests