name: "Windows: cl on x86_64 "

on:
  push:
    branches: [ "main" ]
    paths:
     - '**/*.cpp'
     - '**/*.h'
     - '**/CMakeLists.txt'
     - '**/*.yml'
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025
    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        library_share: [TRUE, FALSE]
          
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DBUILD_SHARED_LIBS=${{ matrix.library_share }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{matrix.build_type}}
